### ISSUE TITLE
Classeur testing

### ISSUE THREAD

**Issue by mycyberacademy** [classeur/classeur#1]
Hello, i just saw the Classeur beta app and looks promising. 

I was playing with it for a while and i didn't found a "box" to insert custom extensions like stackedit does.

My main goal is to insert an existing extension i've created that convert this:

```
<pre><code> 
// some code here
</code></pre>
```

to this: 

```
<pre class="prettyprint">
// some code here
</pre>
```

That HMTL output is how my blog shows code snippets correctly.

There is a way of doing that? If no, do you have plans to add custom extension to classeur like stackedit does?

My other question is. Do you plan to assign shortcuts to buttons? That along with an snippet creation mechanism would be great.

**Comment by benweet** [comment]
Hi @mycyberacademy 

Thanks for your feedback.

I've just created a new issue for the custom extension support: https://github.com/classeur/classeur/issues/2 and another one for the shortcuts: https://github.com/classeur/classeur/issues/3.
