### ISSUE TITLE
Sharing post w/ private OR public link doesn't work

### ISSUE THREAD

**Issue by mbox5** [classeur/classeur#10]
I've tried now to share several different posts and the link that the system produces - either the private or public links, neither one of them works. Instead, the links takes me to the online editor.

**Comment by benweet** [comment]
Hi @gpbak,

Are you trying to collaborate with other people on that file? Or do you want to share a link to your blog?

The share link is to share access to the file in the editor. It's mostly for collaboration or if you want some people to review your file before publishing.
To share a link to your blog, you have to post your file to the blog and then go to menu>"post to blog", click the "open blog post" icon to actually go to your blog page and share the url from there (not that convenient at the moment...).

**Comment by coelhoricardo** [comment]
In my case, the "read only" link redirect to "my first file" with a toaster saying "file not accessible".

**Comment by benweet** [comment]
Reproduced. Investigating...

**Comment by benweet** [comment]
Fixed.

**Comment by coelhoricardo** [comment]
:thumbsup:

**Comment by mbox5** [comment]
Excellent!
