### ISSUE TITLE
Export to PDF doesn't really work...

### ISSUE THREAD

**Issue by torbjornlager** [classeur/classeur#103]
I have a folder with 16 documents, each a chapter in a book. Out of these, only 6 can be converted into PDFs. For the remaining 9 I don't even get an error message. What might be the problem?

Best regards,
Torbjörn

**Comment by benweet** [comment]
Hi, can you provide a markdown sample to reproduce the problem?

**Comment by torbjornlager** [comment]
Can I zip the 9 docs up and send them to you (privately). Or alternatively,
pass you the link to the read-only view of them. Would that work? In that
case, I need an address.

On Sun, Mar 20, 2016 at 11:28 AM, Benoit Schweblin <notifications@github.com

> wrote:
> 
> Hi, can you provide a markdown sample to reproduce the problem?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/classeur/classeur/issues/103#issuecomment-198890049

## 

Torbjörn Lager
Professor of General and Computational Linguistics
Department of Philosophy, Linguistics and Theory of Science
University of Gothenburg
Box 200, SE-405 30 Gothenburg, Sweden
Phone: +46317864962

**Comment by torbjornlager** [comment]
Here's a link to the read-only view of one of the docs (in the hope that fixing this one will fix the others as well):

https://app.classeur.io/#!/files/UwMEE2zqmOejnr4QbZZz

**Comment by hustwj** [comment]
I have the same issue of "export to pdf".

**Comment by benweet** [comment]
Should be fixed with version 1.2.2 (version is shown in the help dialog)
