### ISSUE TITLE
Move documents between files

### ISSUE THREAD

**Issue by vagelim** [classeur/classeur#105]
Currently, there is no option to move documents between organizational "files" as they are called in-app. Personally, I like to keep separate "files" (aka folders) for active and completed projects. The current functionality does not enable this use case.

**Comment by benweet** [comment]
Hi,
- Files can be moved from one folder to another using drag and drop.
- Folders can be moved (or copied) from one classeur to another using the "Import..." button in the "new folder" dialog (see the "+" button on the right side of the classeur).

Hope it helps.

**Comment by vagelim** [comment]
:+1: sorry, was looking in the dot menu for the option.
