### ISSUE TITLE
Classeur just merged all my classeurs!

### ISSUE THREAD

**Issue by arm32x** [classeur/classeur#106]
I used to have lots of classeurs, and now they're like this!

![screenshot 2016-03-24 at 1 03 43 pm](https://cloud.githubusercontent.com/assets/15364665/14024704/e10a4ee0-f1c0-11e5-8848-9ca358151f2a.png)

**Comment by benweet** [comment]
Must be because of the last 1.0 update.

The format of the classeurs has changed. The upgrade procedure was supposed to be transparent. Obviously not bulletproof.

Sorry about that.
