### ISSUE TITLE
Files by Folder not working

### ISSUE THREAD

**Issue by dotsomeone** [classeur/classeur#107]
When we try to add a new file to a folder, it is not listed for that folder. Instead, it is showing all files or recent files from all the folders.

**Comment by benweet** [comment]
Can you tell us what are the steps to reproduce the issue?
Many thanks

**Comment by benweet** [comment]
Not reproduced

**Comment by geckolinux** [comment]
Hi, I'm seeing the same issue. I have three folders, and they all show all the documents.
