### ISSUE TITLE
Excessive CPU Usage

### ISSUE THREAD

**Issue by remexre** [classeur/classeur#108]
When Classeur is the currently selected tab in Chrome, CPU usage reaches 100% for its tab. Issue exists on the latest Chrome OS (as of 2016-04-11) and my Linux system (Google Chrome 49.0.2623.112).

**Comment by telen** [comment]
Same problem as I met, Mac 10.11.4 Chrome 50.0.2661.94
It seems like that it continue scaning the editing text area, perhaps add some throttle method to lower the CPU usage.

**Comment by orschiro** [comment]
Thanks for your reports @telen and @remexre!

We will look into it. 

~Robert

**Comment by sbrl** [comment]
Yep, I see this issue too. It causes my laptop to heat up quite considerably - I'm going to have to use stackedit instead until this issue is resolved. Here's my `uname -a`:

```
Linux Snowflake 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by orschiro** [comment]
Thanks @sbrl!

Stackedit doesn't have this issue?

~Robert

**Comment by sbrl** [comment]
@orschiro Nope! Not that I can see.

**Comment by orschiro** [comment]
Dear @sbrl and others, 

We will see how we can address this issue. 

Please give us some time. 

Thankfully,

~Robert

**Comment by sbrl** [comment]
@orschiro Thanks! As soon as it's fixed, I'll be a huge fan of classeur :D

**Comment by DavidPrada** [comment]
Same problem exists in the OSX versión

**Electron Helper** process reaches 98% CPU usage

**Comment by benweet** [comment]
Should be fixed in the latest release. Please let us know if you experience it again.

**Comment by sbrl** [comment]
I'll check classeur.io again when I get home. Thanks!

**Comment by sbrl** [comment]
Took me a while to get back to you, but it looks good!

Thanks for fixing this.

**Comment by orschiro** [comment]
Great to hear, @sbrl!

Thanks for your feedback. :smiley: 

~Robert
