### ISSUE TITLE
Can't connect to IndexedDB

### ISSUE THREAD

**Issue by dcostas** [classeur/classeur#109]
When i open app.classeur.io (Firefox Debian) open a message "Can't connect to IndexedDB" and not working.

**Comment by benweet** [comment]
Hi,
Can you make sure you're running the latest version of Firefox?

**Comment by dcostas** [comment]
Hi,
in the lastest version of Firefox (49) work fine. 

Thanks

**Comment by orschiro** [comment]
Great, thanks!
