### ISSUE TITLE
Publish to medium.com

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#110]
Dear @benweet,

What do you think of adding an option to publish content to [medium.com](https://medium.com/)?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14598563/153bcda6-0553-11e6-89a6-ca82ed1e082e.png)

**Comment by benweet** [comment]
Hi @orschiro 
Yes I think we should have a ticket to follow the different blogging platform we could support. A todo list with at least the following:
- [ ] Dropbox
- [ ] Tumblr
- [ ] medium.com
- [ ] zendesk articles

**Comment by orschiro** [comment]
Hi @benweet,

Great list for the time being. This should cover the most interesting use cases. 

I did some investigation and couldn't find any other Markdown editor that allows publishing to Wordpress or Medium (by the way). 

Warmly,

~Robert

**Comment by buckle2000** [comment]
Also [Tumblr](https://www.tumblr.com/) please!

**Comment by benweet** [comment]
It looks like it's not possible at the moment as there is no way to update a post with the current API:
https://github.com/Medium/medium-api-docs/issues/22

**Comment by benweet** [comment]
Closing this in favor of https://github.com/classeur/classeur/issues/123.
