### ISSUE TITLE
PDF export fails

### ISSUE THREAD

**Issue by harpone** [classeur/classeur#111]
I've been unable to export to PDF for over two weeks now... it just hangs at "Your document is being prepared...". Txt exports etc seem to work fine.

I also created a new test document and first tried export with text only => worked, then with text and LaTeX => worked, then with also a .png => worked, then another .png image => didn't work. After this it doesn't work even if I remove all the images and LaTeX...

**Comment by benweet** [comment]
Hi, can you try again with latest update (v1.2.2 in the help dialog).
If not better can you provide a sample document to reproduce the issue?
Thanks

**Comment by harpone** [comment]
OK now I got at least a valid error:

`! LaTeX Error: Bad math environment delimiter. See the LaTeX manual or LaTeX Companion for explanation`

So it was probably that all along (?). Need to find the LaTeX error somehow and then try again...

**Comment by harpone** [comment]
Found it, it was my mistake all along: I had used \begin{equation} and \end{equation} instead of the dollar signs at one equation... fixed that and now it works fine! Would be nice if the error message corrected somehow to the error position, but eventually I was able to find the place based on the error message...
