### ISSUE TITLE
Garbled words in document

### ISSUE THREAD

**Issue by johnaxel** [classeur/classeur#113]
I just opened a file I haven't touched in several days, and words are garbled throughout. Restoring a previous version of the file doesn't seem to fix the problem, either.

**Comment by johnaxel** [comment]
Examples: 
summary --> "ssummar"
particular --> "particula r"
metrics --> "metricsss"

The weird thing is the corruptions are consistent (all usages of "summary" have become "ssummar"), as if a global find/replace had occurred.

**Comment by benweet** [comment]
Weird. Can you provide us with the file ID? You can send it by email if you don't want to post it here: benoit@classeur.io
Thanks

**Comment by johnaxel** [comment]
Sure -- will follow up over email. Thanks.

**Comment by benweet** [comment]
Hi @johnaxel 
We couldn't reproduce the bug. It may be due to an upgrade of the app.
Have you experienced this again?

**Comment by johnaxel** [comment]
Hasn't happened again, but I'll let you know if it does. Thanks for looking
into it.

**Comment by orschiro** [comment]
That's great to hear, thanks @johnaxel! :-)

**Comment by benweet** [comment]
Hi @johnaxel  
We were able to reproduce the problem ourself. We deployed a fix (in v1.4.0) so this shouldn't happen again.
Sorry again.

**Comment by johnaxel** [comment]
Thanks for the update @benweet !
