### ISSUE TITLE
Grammarly: losing line breaks when returning from Grammarly

### ISSUE THREAD

**Issue by johnecobo** [classeur/classeur#115]
Grammarly injects a link in one's documents written in web form. Clicking will take you to a Grammarly page where it will suggest grammar and spelling corrections. This works fine with most tools and sites.

However, with Classeur, when returning from Grammarly, I find that all the carriage returns are missing and am left with one big line of text.

I don't know if the issue is with Grammaly or Classeur, but I've never seen the problem before.

**Comment by orschiro** [comment]
Dear @johnecobo,

Could you guide me through the process in order to reproduce the problem?

Thanks!

~Robert

**Comment by johnecobo** [comment]
Steps to re-create the problem:
1. sign up for Grammarly (I have a paid account)
2. obtain the Grammarly app, "Grammarly for Chrome"
3. use Classeur in Chrome writing some Markdown, make grammar and spelling mistakes
4. a small green Grammarly button will appear in the Classeur editor, click it
5. your document will be loaded into a pop-up Grammarly editor with Grammarly grammar and spelling suggestions.
6. exit Grammarly with the button on the top-left
7. I find (usually) that I have now lost all carriage returns and the markdown document is a mess, all on one long line.

---------------------------------------------------------this document:

# this is a test
1. of the American 
2. broadcast 
3. system 
4. why 
5. oh, why 

I could writee forever and ever without failing I suppose but it might be a long long long time.

--------------------------------------------------------became this:

# this is a test 1. of the American 1. broadcast 1. system \* why \* oh, why I could writee forever and ever without failing I suppose but it might be a long long long time.

**Comment by orschiro** [comment]
Thanks @johnecobo!

I can confirm the issue in this screencast:

https://cloudup.com/cwabCCJB8-s

@benweet do you have any idea what is causing the issue?

Warmly,

~Robert

**Comment by benweet** [comment]
Reproduced!
Investigating...

**Comment by benweet** [comment]
I'm afraid the Grammarly app is too intrusive. There are multiple problems with it. The biggest one: it breaks the whole layout with some weird scrollbars.

Sorry we can't support that.

By the way, @orschiro your link doesn't work :)

**Comment by johnecobo** [comment]
That is too bad. Being able to dip into Grammarly is something I find extremely useful as it saves the first cut of editing and proofreading.

**Comment by orschiro** [comment]
Hi both, 

I will get in touch with Grammarly to make them aware of the problem. 

Maybe they have an idea!

~Robert
