### ISSUE TITLE
Numbered lists are continued in new sections

### ISSUE THREAD

**Issue by matsair** [classeur/classeur#118]
Hey,
Numbered lists are continued even after that list was finished. I noticed this in the Mac Desktop app, not sure if it happens in the web app.
Example:

```
    1. Item one
    2. Item two
    3. Item three
    ### Heading
    Body
    4. If I type 1. it auto-corrects to 4.
```

**Comment by orschiro** [comment]
Dear @matsair,

Thanks for raising this issue. 

I can confirm it. Annoying bug!

Warmly,

~Robert
