### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by Swader** [classeur/classeur#12]
Random conflicts keep occurring, bringing back previous versions for no apparent reason.

For example, I'm working on a post then I procrastinate and fly off to other tabs for 30 minutes or so, and when I come back, almost every time, the post will be packed with conflicts from a while back. Not only conflicts with itself (like a paragraph I changed in the post) but also conflicts with the original welcome post - entire segments conflicting the "Welcome to classeur" message with paragraphs in my post.

Is there anything I can do to mitigate this and make sure it considers the currently opened document latest at all times? I only have it open in one tab, it's not open elsewhere.

**Comment by benweet** [comment]
Hi @Swader 
Thanks, I'm reproducing it. Investigating...

**Comment by benweet** [comment]
Should work as expected now. I keep it open though as this has to be fixed properly.

**Comment by benweet** [comment]
Just fixed the bug.
