### ISSUE TITLE
\label and \eqref or \ref don't work

### ISSUE THREAD

**Issue by harpone** [classeur/classeur#121]
Newest MathJax should support those... it does seem to try to do something, but I just get (???) and formula with the \label will break down...

or maybe it should work and I'm doing something wrong?

EDIT: here's an example:

```
Here is the formula:
\begin{equation}
E = m c^2 
\label{eq:formula}
\end{equation}
According to formula \eqref{eq:formula}, energy is blablabla...
```

I guess the \label just breaks the equation... happens for both the \begin... \end or just when using $$...$$.

**Comment by orschiro** [comment]
Thanks for your report, @harpone!

Can you please provide an example that we can try to reproduce?

Thankfully,

~Robert

**Comment by harpone** [comment]
edited the first post accordingly

**Comment by orschiro** [comment]
If I try to export your above code as PDF, I get the following error: 

![image](https://cloud.githubusercontent.com/assets/170947/15827576/f55dac72-2c0b-11e6-8dc6-6d449a06ce3f.png)

**Comment by harpone** [comment]
Oops yeah that happens for me too... anyway, same problem with the double dollar signs (which is what I did earlier):

```
Here is the formula:
$$
E = m c^2 
\label{eq:formula}
$$
According to formula \eqref{eq:formula}, energy is blablabla...
```

**Comment by orschiro** [comment]
Confirmed. 

Although the export works with Dollar signs. 

![image](https://cloud.githubusercontent.com/assets/170947/15886813/41e113aa-2d5f-11e6-87c0-9e0ddd823cc3.png)

Warmly,

~Robert

**Comment by benweet** [comment]
Hi @harpone 
I'm afraid Classeur doesn't support label referencing, nor does any tex/markdown editor I know (stackedit, math.stackexchange.com...)
As a workaround, markdown headers can be used as labels: `[go to my header](#my-header-title)`
