### ISSUE TITLE
Cannot post to Blog

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#124]
Received as a Zendesk ticket:

> I tried to post to blog, but after click on the button 'publish' happens nothing.. Modal window jist closes. When i watched in dev tools I saw following:
> 
> GET https://app.classeur.io/1.3.3/templateWorker-min.js [HTTP/1.1 404 Not Found 405ms]
> NetworkError: Failed to load worker script at "1.3.3/templateWorker-min.js" (unknown)
> 
> :/
> 
> $ curl -v https://app.classeur.io/1.3.3/templateWorker-min.js
> - Trying 52.200.32.200...
> - Connected to app.classeur.io (52.200.32.200) port 443 (#0)
> - found 173 certificates in /etc/ssl/certs/ca-certificates.crt
> - found 704 certificates in /etc/ssl/certs
> - ALPN, offering http/1.1
> - SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
> - server certificate verification OK
> - server certificate status verification SKIPPED
> - common name: *.classeur.io (matched)
> - server certificate expiration date OK
> - server certificate activation date OK
> - certificate public key: RSA
> - certificate version: #3
> - subject: OU=Domain Control Validated,OU=PositiveSSL Wildcard,CN=*.classeur.io
> - start date: Sun, 05 Jul 2015 00:00:00 GMT
> - expire date: Mon, 04 Jul 2016 23:59:59 GMT
> - issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
> - compression: NULL
> - ALPN, server did not agree to a protocol
>   > GET /1.3.3/templateWorker-min.js HTTP/1.1
>   > Host: app.classeur.io
>   > User-Agent: curl/7.47.0
>   > Accept: _/_
>   >
>   < HTTP/1.1 404 Not Found
>   < Server: nginx/1.9.9
>   < Date: Sun, 12 Jun 2016 00:14:37 GMT
>   < Content-Type: text/html; charset=utf-8
>   < Content-Length: 40
>   < Connection: keep-alive
>   < X-Powered-By: Express
>   < X-Content-Type-Options: nosniff
>   < Vary: Accept-Encoding
>   <
>   Cannot GET /1.3.3/templateWorker-min.js
> - Connection #0 to host app.classeur.io left intact

**Comment by clickfreak** [comment]
Thanx!
