### ISSUE TITLE
Post completely garbled: possible sync issues?

### ISSUE THREAD

**Issue by harpone** [classeur/classeur#126]
I was working on a post and shared it to multiple co-workers for commenting. Today at around 2PM GMT+2 the post quickly got more and more garbled, basically turning most of the text into gibberish. It seemed to occur at places where others had commented...

Is it possible to discuss with someone about this privately? Are there any backups/logs etc?

**Comment by benweet** [comment]
Hi @harpone 
You should be able to recover previous versions in the history tab (the last tab in the side bar).
Some other users have reported this issue. We're investigating.

**Comment by harpone** [comment]
OK found the history... unfortunately all the versions seem to be garbled... also I get an error "File is too big!"

**Comment by harpone** [comment]
Luckily I had downloaded a version last thursday, but basically all the changes since are lost, since the history is broken too... is there any way to fix this??

**Comment by harpone** [comment]
Just as a clarification: I'm writing a company blog post which should be out on Wednesday, so this is pretty urgent to say the least...

**Comment by benweet** [comment]
Can you send me the file ID to my personal address: benoit@classeur.io

**Comment by harpone** [comment]
OK thanks, fixed!

**Comment by benweet** [comment]
Hi @harpone 
We were able to find a pattern to reproduce the problem ourself. We deployed a fix (in v1.4.0) so this shouldn't happen again.
Sorry again.

**Comment by harpone** [comment]
OK great good to hear! :)
