### ISSUE TITLE
Is it possible to preserve mathjax $$ tags when exporting to HTML?

### ISSUE THREAD

**Issue by harpone** [classeur/classeur#127]
Currently Classeur (using pandoc?) seems to replace all formulae inside double dollars etc. with javascript snippets, which don't play nice with e.g. Wordpress' visual editor (the editor automatically inserts some CDATA tags which screw up mathjax...).

Seems like I could do something with the Templtes, but can't figure out what...

**Comment by benweet** [comment]
Yeah we should probably keep the original formulae in the export and let mathjax do the job on the blog site.

**Comment by harpone** [comment]
It's actually pretty cool though that all the mathjax configs etc. is already in the export though... so maybe just a different export options for the user would be the best choice (i.e. with $$...$$ or replace by javascript).
