### ISSUE TITLE
[TOC] does not work with exporting

### ISSUE THREAD

**Issue by buckle2000** [classeur/classeur#129]
`[TOC]` will be converted into table of contents only in online preview, but not in exported pdf or Word documents.

**Comment by orschiro** [comment]
Dear @buckle2000,

Thank you for the report! I could confirm it and mark it as a bug. 

~Robert

**Comment by benweet** [comment]
`[TOC]` marker is deprecated, Pandoc doesn't support it. However there is an option to generate proper pandoc TOC in the settings.

**Comment by buckle2000** [comment]
@benweet I know there is a setting, but what if I want to generate table of contents at where `[TOC]` is, not the beginning of a article?

**Comment by benweet** [comment]
Hi @buckle2000 

It may be possible via a custom PDF template, that would be related to this issue: https://github.com/classeur/classeur/issues/125.
