### ISSUE TITLE
proposal: Version Control

### ISSUE THREAD

**Issue by buckle2000** [classeur/classeur#130]
What does the History tab in the slide bar do?
A linear version control system is needed for some cases in academic writing.
A version control like Git is powerful both in solo and cooperating.

What's more, an article can **either** stored at [classeur.io](https://classeur.io) or any version control service like Github, reducing pressure on [classeur.io](https://classeur.io). Then one can just pull the file to local computer and work with any text editor one prefers, offline, no browser needed.

**Comment by benweet** [comment]
Hi @buckle2000 
You can use history tab to:
- see who modified the file
- retrieve previous version of the file

There is already a ticket for Github synchronization here: #114.
Please open another ticket if you are missing some other features.
