### ISSUE TITLE
Could not find image

### ISSUE THREAD

**Issue by developius** [classeur/classeur#133]
I get this after trying to export as a PDF
![screen shot 2016-06-25 at 17 20 28](https://cloud.githubusercontent.com/assets/5836587/16358101/9bd4ca0a-3b01-11e6-9527-480412b74a68.png)

**Comment by benweet** [comment]
Hi
Do you have non public images in your file, such as image stored on dropbox?

**Comment by developius** [comment]
Not as far as I know, it's one uploaded to Imgur via the upload button in the app itself.

**Comment by benweet** [comment]
Can you share a file to reproduce the issue?

**Comment by developius** [comment]
Sure, this is the file: https://app.classeur.io/#!/files/ZyTIY3tFG6iOCtVpi836
It doesn't seem to happen for Word exports and it doesn't happen for any of my other files :(

**Comment by benweet** [comment]
You have an empty `![]()`, it works if you remove it.
It's a bug though, it shouldn't fail.

**Comment by developius** [comment]
Ahhh, brilliant - thank you!

**Comment by benweet** [comment]
Fixed in v1.5
