### ISSUE TITLE
Error when trying to login to google using self hosted version

### ISSUE THREAD

**Issue by sverley** [classeur/classeur#134]
I am using classeur in the self-hosted version (`npm start` then use firefox to go to url `http://localhost:11583`).
It seems to work correctly but when I click on "SIGN IN WTH GOOGLE", I get this error:

```
400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Missing scheme: undefined/oauth/google/callback

Learn more
Request Details

    scope=profile email
    response_type=code
    redirect_uri=undefined/oauth/google/callback
    state=tCv5QQMWMaepJaUeEoFT.1467386899214
    client_id=undefined

That’s all we know.
```

The `Learn more` leads me to [this page](https://developers.google.com/identity/protocols/OAuth2)

I have to specify that I am behind a proxy, which is well configured in firefox and in my gnome environment.

**Comment by benweet** [comment]
Hi @sverley 
I'm afraid you have to use Classeur Enterprise to have access to connected features (login/sync/publish...).
