### ISSUE TITLE
Question: Is This Possible?

### ISSUE THREAD

**Issue by pastorryanhayden** [classeur/classeur#135]
My company makes affordable websites for churches.  We actually use airtable as a CMS, and have scripts that build the sites locally by pulling down and parsing that data and then using a static site generator to render the site and push it to a cdn for hosting.  One of the principles that we are committed to is we try to use tools that can be used elsewhere in a church ministry.
I've looked through your API documentation and I was wondering if what I'm thinking is even possible.  I'd like to set it up so that classeur posts to an airtable field.  (Airtable uses a simple rest api and you can post json to it).  Basically, airtable would be where the site is managed and classeur would then become the default place where the client does his markdown writing.
Without knowing the airtable api, does this sound like it's possible?

**Comment by orschiro** [comment]
Thanks for your question @pastorryanhayden!

This sounds like an Enterprise request to me. 

@benweet, what do you think?

Warmly,

~Robert

**Comment by benweet** [comment]
Hi @pastorryanhayden 

To me, it sounds like your want to use Airtable as a blogging platform? If so, it would be a candidate for https://github.com/classeur/classeur/issues/123.

Can I ask you why use Airtable as a CMS and not wordpress or an actual CMS?
