### ISSUE TITLE
Bug: Scroll Sync and ToC broken in Firefox

### ISSUE THREAD

**Issue by VillageHubertChen** [classeur/classeur#136]
# How the Bug Shows
1. Open a long enough document in Classeur in FireFox
2. Set preference like so:
   - _Side Preview:_ On
   - _Side Bar:_ On
   - _Scroll Sync:_ On
   - Configure side bar to show ToC (Table of Contents)
3. Scroll in the edit pane
4. Bug 1: Preview pane does not scroll
5. Bug 2: Clicking a Heading in ToC does also not scroll
# Additional test reports
- A few days ago this was working
- Even today when it does not work in FireFox it does work in Chrome
# My Configuration
- _OS:_ Win 7-64 bit, English, all updates installed (including from last night)
- _Firefox:_ Version 47.0
# Compliments

Thank you so much for Classeur! It is one of the Apps I use every day. I very appreciate the direction your App development is going. Especially that you can use several documents in parallel. Also the recent improvements on file management were very useful. The new cosmetics are very nice too. Great job!

I am very sorry I was facing the above bugs. In case this was caused by my stupidity, please be so kind to enlighten me.

**Comment by orschiro** [comment]
Thank you for your compliments, @VillageHubertChen! :smiley: 

We are also going to invest this issue, 

~Robert

**Comment by VillageHubertChen** [comment]
You are welcome! Thanks for letting me know you are working on it. I'd appreciate if you write a comment in here to let me know when the bug is fixed.

**Comment by VillageHubertChen** [comment]
Dear Robert,

You can close this issue. You solved it via → #138 . Thanks so much!

~ Hubert

**Comment by orschiro** [comment]
Closed. :-)
