### ISSUE TITLE
Bug: ToC not working when longer than page height

### ISSUE THREAD

**Issue by VillageHubertChen** [classeur/classeur#137]
# How the Bug shows
1. Load a long document in Classeur with lots of headings. 
2. To reproduce this issue the Table of Content pane need to have a longer table of content than fits into the vertical height of the page.
3. Scroll down the ToC pane. Click on a heading. Either the edit pane does not scroll at all, or does scroll to the wrong heading
4. Just to show that this is related to scrolling the ToC pane: Scroll up the ToC pane. Now it works!
# Additional test reports
- The bug is browser independant, no matter if I use FireFox or Chrome
- Reproduced on a second PC
# My Configuration
- _OS:_ Win 7-64 bit, English, all updates installed (including from last night)
- _Firefox:_ Version 47.0

**Comment by orschiro** [comment]
Thank you for reporting this bug, @VillageHubertChen!

We will investigate it. 

Warmly,

~Robert

**Comment by VillageHubertChen** [comment]
Dear Robert,

You are very welcome! Let me know if there is anything else I can do, like further testing following your instructions.

Good hunting,

Hubert

**Comment by VillageHubertChen** [comment]
Dear Robert,

This bug was not fixed with → #138 (Console Error). However, you can use the long markdown text I posted in the comment to #138 to reproduce it. Using the same text in stackedit worked. Meaning the feature of using that long document and handling the Table of Contents (ToC) linking fine when scrolling down a long ToC lists.  

Do you have any timeline when this could be fixed? I am anxious to go back using Classeur :-)

Thanks again for your wonderful app and your swift support,

Hubert

**Comment by orschiro** [comment]
Dear Hubert, 

You're right. Indeed, if the TOC is scrolled to the bottom, then clicking on a referenced heading leads to the wrong reference. 

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/16907095/9d978320-4cc0-11e6-9d68-58ebf441b0b3.png)

**Comment by VillageHubertChen** [comment]
Dear Robert,

Thanks so much to let me know you can reproduce the bug. Any idea on the ETA of a fix?

~Hubert

**Comment by benweet** [comment]
Should be fixed in the next release in a week or so.

**Comment by VillageHubertChen** [comment]
Thanks!

**Comment by VillageHubertChen** [comment]
Hi, any new estimates on the new release fixing this bug?

**Comment by VillageHubertChen** [comment]
Hi Ben,

thanks very much. I confirm it works :-)
