### ISSUE TITLE
How to use Handlebar helpers?

### ISSUE THREAD

**Issue by vladejs** [classeur/classeur#140]
Classeur doesn't convert my helpers into what I want, or I am doing something wrong.
Both in the app and [here](https://classeur.zendesk.com/hc/en-us/articles/208710309-Templates) are examples of helpers, but it doesn't show how to apply them in the document.

I tried this:

```
Handlebars.registerHelper('bold', function(options) {
  return new Handlebars.SafeString(
      '<div class="mybold">'
      + options.fn(this)
      + '</div>');
});
```

And in the editor I wrote:

```
{#bold}} Text {{/bold}}.
```

It doesn't work.

**Comment by benweet** [comment]
Hi @vladejs 

Handlebars helpers are only used in export/publish templates. This is how your template would look like:

```
{{#bold}}{{file.content.text}}{{/bold}}
```
