### ISSUE TITLE
Suggestion: Night mode

### ISSUE THREAD

**Issue by sbrl** [classeur/classeur#143]
Thanks to your efforts fixing my earlier issue (can't find it now) with high resource usage, I've started to use classeur regularly for writing posts for my blog, switching over from [Stackedit](https://stackedit.io/editor). It's been a great experience so far (love the side by side preview, although I can't figure out what "Zen Mode" does).

When I take too long over writing a blog post, since I've got natural light at the moment due to it being summer up here in the north, the sky has this awful habit of going dark. Apart from being midly annoying, this also has the added side effect of making classeur.io appear way too bright, even with my monitor brightness turned way down. Since I'm usually in the middle of a paragraph, I don't want to get up and turn the light on, so it would be really helpful if classeur had a night, or dark, mode that could be toggled via a keyboard shortcut.

**Comment by orschiro** [comment]
Dear @sbrl, 

Thanks for your request!

Closing this in favour of [1].

Please feel free to follow-up there. 

And I will make sure to create an article in the FAQ [2] to explain what Zen Mode ist. Thanks!

[1] https://github.com/classeur/classeur/issues/11
[2] https://classeur.zendesk.com/hc/en-us/sections/201884219-FAQ

**Comment by sbrl** [comment]
Thanks @orschiro :smile:
