### ISSUE TITLE
support different markdown flavors for export

### ISSUE THREAD

**Issue by christian-steinmeyer** [classeur/classeur#149]
There are many flavors of markdown out there, such as the ones on github.com or gitlab.com
It would be great to be able to chose one of those instead of the default, without having to add a custom css.
I know that there is [a plugin for IntelliJ IDEA](https://plugins.jetbrains.com/plugin/7701?pr=clion) that does exactly that for github flavored markdown. That might help.

**Comment by orschiro** [comment]
Thank you Christian!

**Comment by benweet** [comment]
Hi @christian-steinmeyer 
Do the markdown extensions cover your needs?
https://classeur.zendesk.com/hc/en-us/articles/209439105-Extensions

**Comment by christian-steinmeyer** [comment]
Hi @benweet 
As I understand, the extensions provide functionality. To make my request more precise: I'm interested in the format (CSS) of the rendered document only. I believe classeur has done a great job with its clean design, but some might prefer the github flavored style.

**Comment by benweet** [comment]
Hi @christian-steinmeyer 
You can't change the CSS inside the application (unless you use some browser extensions), but you can always customize the CSS of your exports via templates:
https://classeur.zendesk.com/hc/en-us/articles/208710309-Templates
Hope it helps.

**Comment by christian-steinmeyer** [comment]
I saw that. I was just wondering, whether classeur could offer some alternatives to the current file designs.

**Comment by benweet** [comment]
I'm afraid there is no alternative at the moment and no plan for that.
