### ISSUE TITLE
Random cloning of selected text when using hotkeys

### ISSUE THREAD

**Issue by Swader** [classeur/classeur#15]
When I select a bit of text and punch CMD / Control + L to turn it into a link, sometimes the selected text gets clones on either side of the selection. This happens at random.

Example: In the sentence "This is a link", selecting "is a" and pressing CMD + L would, on some occasions, create "This is ais ais alink". Regardless of whether the link is added or the link adding is canceled, this happens - in the former case, the link is inserted between the clones.

**Comment by Swader** [comment]
Here's a gif of the issue.
![classeur-dupe](https://cloud.githubusercontent.com/assets/1430603/10714830/4fdbe320-7b00-11e5-86ce-78769703c171.gif)

**Comment by benweet** [comment]
Thx. I'll have a look asap

**Comment by jwarner112** [comment]
Confirming, this bug happens for me as well.
