### ISSUE TITLE
can't not post to blogger

### ISSUE THREAD

**Issue by Yang-025** [classeur/classeur#151]
Link to blogger is ok 
But publish article not work 

![2016-08-02 8 09 08](https://cloud.githubusercontent.com/assets/7609053/17327865/09f1410e-58ed-11e6-80c5-965e83ca9c06.png) 

![2016-08-02 8 10 23](https://cloud.githubusercontent.com/assets/7609053/17327897/2dd2a46e-58ed-11e6-80a4-cad9cdf05421.png)

**Comment by orschiro** [comment]
Dear Yang, 

Thanks for your bug report!

@benweet how can we debug this?

**Comment by Yang-025** [comment]
@orschiro Today I create a new blogger. And publish article success.  And I try the the old blogger, also success,too

**Comment by orschiro** [comment]
Thanks for your reply! I will mark this as solved then. :-)
