### ISSUE TITLE
How to Export ToC ?

### ISSUE THREAD

**Issue by VillageHubertChen** [classeur/classeur#156]
Dear Robert,

I wanted to discuss this at a later time, but since this issue came up now and since Ben is probably about to look at this part of the code, I thought this might be a good time to bring it up:

Adding _Table of Content Export_ should be very straight forward and to those who need it, it is a real godsend. At the bottom is a link to source code and demo from us which might be useful. (We don't claim it is great code, but it works :-) )
# Do you have Export ToC and I can't find it?

I found in Classeur > Settings > App > Export the settings:
1. Pandoc TOC
2. Pandoc TOC depth

I could not find however to only export the TOC. Or is this simply meant as the settings for the ToC within the Pandoc export process?

If so, then this is no time save over Plain HTML export, as the TOC still need to be manually extracted from the HTML source code.
# Why anyone would want to export TOC?

Some publishing systems simply need the TOC in the form of JSON or JAML when publishing the Article.
# How to generate now?

Tedious 10 step procedure to add [TOC] create HTML export and extract the HTML UL TOC from source code.
# Suggested Feature Implementation

In case you do not have a TOC export, it would be great if you add this feature. 

You could add this to your existing Export Requester as third topic:
## Export Requester:
- **Text:** (Plain HTML | Plain text | Styled HTML)
- **Document:** (EPUB | EPUB v3 | LaTeX | OpenOffice | PDF | Rich Text For ... | Word )
- **Table of Contents:** ( HTML | JSON | YAML | Markdown )
## How User Manual would look like
1. Go to Menu and press "Export"
2. In the Export Requester tick: "Table of Contents"
3. Choose your Table of Contents format: ( HTML | JSON | YAML | Markdown )
4. Press the "EXPORT" button
5. A Requester with a text box opens. Copy the generated ToC to your clipboard and paste it where you need it.
## How to Code HTML TOC

Use the code you already have to generate the `<div class="toc">` in HTML preview.
## How to generate JSON & YAML

Use the code from this project: https://v-squared.github.io/v2-ToC-Converter/

If you want us to make any changes and or add the Markdown output, let us know.
# Low hanging fruit?

Classeur really shines in terms of flexibility in export. Adding Table of Contents export should be simple and it addresses the annoying issue to generate Table of Contents by hand or by meddling in source.

Let me know what you think?
# Reference
- → #155

**Comment by orschiro** [comment]
Hi Hubert, 

I like the general idea and I think we could track this even further to allow for the export of individual sections as shown by the following screenshot:

![image](https://cloud.githubusercontent.com/assets/170947/17528294/2416687a-5e6f-11e6-9f13-03cfc0f9adce.png)

@benweet, what do you think?

Warmly,

~Robert

**Comment by VillageHubertChen** [comment]
Hi Robert,

Great! This will actually solve several problems we have right now to create navigation that is:
1. Succinct and allows for fast scanning yet we can write with 3 .. 4 levels of ToC depth.
2. Works equally as well on mobile and big screen
3. Works equally well on a short blog post or a 100 page manual

This way Classeur becomes a very universal writing tool ranging from short blog posts to long manuals and technical papers. **Big Compliments** to this great idea! When can we have it?

**Comment by orschiro** [comment]
Thank you, Hubert. :-)

Well, I guess @benweet is the best person to ask this for. Do you like this idea, Ben? 

~Robert
