### ISSUE TITLE
Compliments and THANK YOU on Sharing!

### ISSUE THREAD

**Issue by VillageHubertChen** [classeur/classeur#158]
Dear Ben & Robert,

I reported so many bugs and asked for many features so I thought it is time to also report a job well done:

In an effort to complete the Classeur manual I turned on document sharing. WOW! Same power as in Google Docs! I did not expected that!

We walked away from Google Docs some time ago. I truly and sorely missed this feature of multiple authors being able to write simultaneously in the same document with multiple cursors. You brought this feature back to our writing team. We are so grateful! And you implementation is beautiful and intuitive too!

THANK YOU!

Hubert

**Comment by orschiro** [comment]
Well, that is **very** nice to read your words. 

Thank you for the attribution! :+1: 

~Robert

**Comment by VillageHubertChen** [comment]
You are welcome. You guys earned it. I will be rewriting the Classeur manual accordingly to make this feature highly visible. It should greatly help your sales :-)
