### ISSUE TITLE
Bug? Discussion is intermittent

### ISSUE THREAD

**Issue by VillageHubertChen** [classeur/classeur#159]
Dear Robert,

I am puzzled by the behavior of _Discussions_. I am describing step by step what I am doing and the results that I am getting. Bottom line: Sometimes my comments show up on the other side, but mostly they do not.
# Turning on Sharing @ Owner
1. Menu > Sharing → Open Requester Sharing.
2. Select:  "public read/write".
3. Send the "Share link" to a second workstation.
# Working on Shared Document @ Colleague
1. Open the link provided by owner.
2. Click the edit button.
3. Start writing in the document. My cursor and my text appear also in the owner's document. This is to proof the connection works.
# Creating a Comment / Discussion
1. Enable Side Bar and select "Discussion".
2. Highlight a word in the editor pane.
3. Click into the bubble that shows to the top right of the highlighted word.
4. In the Side Bar and entry field titled "You" shows.
5. Select the entry field and type a comment and press the "ADD" button underneath.
6. The comment shows as a yellow post it to the left side of the selected word.
# Problem

The comments on one workstation do not show on the other. That is mostly they do not. Sometimes they do. I spend an hour of trying all kinds of things and could not make it work reliably.

Can you please check:
1. Can you reproduce the problem? If so than confirm, mark this as bug and I will wait until fixed.
2. In case it works reliably on your end then please write me what I do wrong in my instructions above in order to enable me to use this feature with reproducible results on our end.

As always many thanks for your help!

Hubert

**Comment by orschiro** [comment]
Dear Hubert, 

Can you please share a document with me that contains your comments?

This way we can collaborate on a document and see whether together we can reproduce the problem. :-)

Thankfully,

~Robert

**Comment by VillageHubertChen** [comment]
Hi Robert,

Great idea!

https://app.classeur.io/#!/files/9Xaz1htCASFFWhk9uULJ

![classeur-testing-comments](https://cloud.githubusercontent.com/assets/7278716/17556147/f02a31e6-5f44-11e6-8f2e-36835e0d36cc.png)

**Comment by orschiro** [comment]
Hi Hubert, 

I got the comment. 

~Robert

**Comment by VillageHubertChen** [comment]
Hi Robert,

I typed my first reply. I typed it when not having internet. After I added the comment I reconnected the internet. Please let me know if you received it. This shall test how well intermittent internet connection is handled. Please reply and also let me know in here if you got it?

~ Hubert

**Comment by orschiro** [comment]
Hi Hubert, 

I received your comment. 

![image](https://cloud.githubusercontent.com/assets/170947/17578558/a5e14016-5f8a-11e6-80da-fb1c53f65a52.png)

**Comment by VillageHubertChen** [comment]
Hi Robert,

I received it. I am at a loss what is different than the other day. This makes 4 out of 4 received. Before I had 1 out of 4. I will now start using it in production with the other team members. If the problem resurfaces again I will let you know. I have no idea what further to test to reproduce the bug? Do you have any more ideas what I can test?

~ Hubert

**Comment by orschiro** [comment]
Hi Hubert,

I have now further ideas as of now. 

Please do open a new issue if the problem occurs again!

Warmly,

~Robert

**Comment by VillageHubertChen** [comment]
Hi Robert,

Thanks & agreed. My apologies for this one. (No need to reply)
