### ISSUE TITLE
does images hosted on imgur expires?

### ISSUE THREAD

**Issue by vladejs** [classeur/classeur#163]
If I publish to my wordpress blog using classeur, the images are shown on the blog with this url:
`http://i1.wp.com/i.imgur.com/kQTeILV.png?ssl=1`. It is safe to keep the blog post that way forever, or should I change the path to my wordpress site?

**Comment by orschiro** [comment]
Dear @vladejs,

Images are hosted on [imgur.com](https://imgur.com/).

Of course, nothing is with certainty but I would assume that images are stored safely there as imgur has been around for quite some years and is known as a reliable image host.

Warmly,

~Robert
