### ISSUE TITLE
Add new WordPress properties for excerpt, featured image, author

### ISSUE THREAD

**Issue by vladejs** [classeur/classeur#165]
I think Classeur is incomplete until it completely automatizes the process of publishing to blog. Currently, to post an article on my blog, I have to always go to my dashboard, click edit post and add manually these properties:
- excerpt: The article's summary that is shown in the blog's main page.
- featured image: The article's featured image.
- categories: Never worked for me in classeur,
- author: If I am my blog's admin, I could publish in place of others 

Do you plan to add them to a classeur properties?

**Comment by orschiro** [comment]
Hi @vladejs,

Thank you for your suggestions!

> excerpt

This could be automatically fetched from the article (e.g. first 200 words)

> featured image

Again, maybe take the first image of a post?

> categories: never worked for me

Can you please specify what did not work?

> author

So, you would like to have a property field to define a specific author's name in the settings?

~Robert

**Comment by vladejs** [comment]
Hi, thanks for your suggestions, but I think those thoughts are pretty
generic. Let's discuss:

> excerpt

Appears as a dedicated box in wordpress, so it makes sense to be a property
field in classeur.

> author

You are right, a property field that matches the username registered on the
blog (i.e: vladejs).

> featured image

Blog writers cares a lot about putting a well crafted featured image for
its blog post, so, most of the time this image is unique (not taken from
the article itself). I think it should be on the post properties like
others.

> categories

If set my categories to match my blog's ones, they aren't set. Instead, the
article gets the default 'General' category.

Categories are a select field in wordpress, so maybe they aren't recognized
by the label itself, but by the `option` value, which may be a database Id.

**Comment by orschiro** [comment]
Hi @vladejs,

Indeed I can confirm that using categories does not work. At least not the way I tried it below: 

![image](https://cloud.githubusercontent.com/assets/170947/17663202/1cc94dd2-62eb-11e6-8464-b75e2a2389b6.png)

Regarding your other good ideas, I will create separate issues for them, if this is fine for you. 

Warmly,

~Robert

**Comment by orschiro** [comment]
Dear all, 

Defining categories as follows does work for me. 

![image](https://cloud.githubusercontent.com/assets/170947/17664324/8db0a042-62f3-11e6-8a3c-8665255bbcc5.png)

**Comment by orschiro** [comment]
I think properties for `excerpt` and `author` are intuitive and easy to implement. 

Regarding `featured image`, should we implement this with the provided value of an external url?

~Robert

**Comment by vladejs** [comment]
It should show the same widget for uploading a regular image using imgur or
an url.

**Comment by orschiro** [comment]
Good idea! :+1:

**Comment by vladejs** [comment]
Any progress with this

**Comment by orschiro** [comment]
@benweet?

**Comment by vladejs** [comment]
@benweet , how would I become a premium user without having these features?

**Comment by benweet** [comment]
Hi @vladejs 
Just added it in the 2.0 milestone.

**Comment by orschiro** [comment]
It should show the same widget for uploading a regular image using imgur or
an url.

##

**Comment by benweet** [comment]
Fixed and deployed in v1.8.
