### ISSUE TITLE
After linking a new blog, return to file

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#166]
Hi @benweet,

Let's assume the following workflow. 
1. Create a new file 
2. Go to menu to publish to a new blog
3. Link a new blog

Currently, Classeur remains at the Settings > Blog screen. 

However, for the user it would be more intuitive and elegant if Classeur returns to the file from `step 1`.

What do you think?

Warmly,

~Robert

**Comment by benweet** [comment]
Hi @orschiro 
I agree. It should be handled as for https://github.com/classeur/classeur/issues/145.
Cheers!

**Comment by orschiro** [comment]
Thanks for referencing #145. I completely forgot about this one. :disappointed: 

~Robert
