### ISSUE TITLE
Improve: Change the "Change Folder" Icon

### ISSUE THREAD

**Issue by VillageHubertChen** [classeur/classeur#170]
## Today

![classeur-change-binder-1](https://cloud.githubusercontent.com/assets/7278716/17999947/4daef7c8-6bae-11e6-85b4-a5087284850e.png)
## Proposed Change

![classeur-change-binder-2](https://cloud.githubusercontent.com/assets/7278716/18000092/035b6278-6baf-11e6-8ea2-36b3d72e5428.png)
## Material Design Icon
- https://design.google.com/icons/#ic_folder
## Survey

I asked 4 people what they think the original icon meant? Four out of four expected a download function. Everybody was surprised that you could create additional folders to manage your articles.

The current icon is hiding a great Classeur feature
## Compliment

I really love the way Classeur manages articles / documents. I can not put a finger on it, but it is fun to use! Great job!

**Comment by orschiro** [comment]
Hi Hubert, 

Thanks for reporting this!

I see why it can cause confusion. 

I will mark this as an enhancement request. 

Warmly,

-Robert

**Comment by benweet** [comment]
Hi @VillageHubertChen 
This will be changed in the next release.
Thanks for your suggestion.

**Comment by VillageHubertChen** [comment]
Hi Ben and Robert,

You are welcome. Thanks for implementing it.
