### ISSUE TITLE
Support import from Blogs

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#172]
Dear @benweet, 

I think we should support the import of articles from linked Blogs, e.g. from Zendesk. 

What do you think?

Warmly,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18035082/52f7446e-6d4e-11e6-8066-60764932a32e.png)

**Comment by benweet** [comment]
Quite complex. Blog articles are in HTML format. Converting HTML to Markdown is not straightforward and error prone.
Closing this.
