### ISSUE TITLE
Difference between Plain HTML and Styled HTML Blogger Template?

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#177]
Dear @benweet,
1. What is the difference between `Plain HTML` and `Styled HTML` Blogger template?
2. How can I make the styled one the default one?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18121818/98553696-6f66-11e6-86dd-46b282b444b3.png)

**Comment by benweet** [comment]
Hi @orschiro 

The "plain HTML" template will generate an HTML file with only simple formatting tags like `<p>`, `<b>`, `<a>`... The is more suitable for blog publications, as blog engines usually wraps the article in a proper HTML page, including the `<html>`, `<head>` and `<body>` tags, stylesheets and javascripts.
On the other hand, the "styled HTML" template wraps the formatting tags into a self contained HTML page including its own stylesheet.

In most cases, you'll have the same result using both templates for your blog publications. In the worst scenario, the "styled HTML" template will produce inconsistent styles across your blog articles and will possibly break the layout of your blog.

My recommendation is to use "Plain HTML" for blog articles publication (you can customize your blog template if needed) and "Styled HTML" for file export.

As for your second question, I've created a separate ticket for that: #183

**Comment by orschiro** [comment]
> My recommendation is to use "Plain HTML" for blog articles publication (you can customize your blog template if needed) and "Styled HTML" for file export.

This is a good idea! Maybe to avoid confusion, don't even offer the "Styled HTML" option when exporting to Blogger or Wordpress. What do you think?

-Robert

**Comment by benweet** [comment]
Yes but templates are [fully customizable](https://classeur.zendesk.com/hc/en-us/articles/208710309-Templates), you can have a styled HTML template named "Plain HTML".
What do you think of having switchable flags in the template editor saying:
- [x] This template can be used for exports
- [x] This template can be used for publications

The second flag would be switched off by default for the "Styled HTML".

By the way, I'm thinking of adding community/sharable templates, as you suggested in #30.

**Comment by orschiro** [comment]
> What do you think of having switchable flags in the template editor saying:

I like it! Let's go for this option together with shared templates. 

-Robert
