### ISSUE TITLE
Fonts account for almost half of the page load time

### ISSUE THREAD

**Issue by sammcj** [classeur/classeur#18]
I'm thinking something could possibly be improved here:

<img width="1695" alt="screen shot 2015-10-27 at 10 33 04 pm" src="https://cloud.githubusercontent.com/assets/862951/10756929/50c607e6-7cfb-11e5-8d2f-0e5fcaa879d4.png">

**Comment by benweet** [comment]
After the first execution, all should be loaded from the application cache:

<img width="863" alt="screen shot 2015-10-27 at 11 54 46 p m" src="https://cloud.githubusercontent.com/assets/1005257/10776083/430bccde-7d06-11e5-9db9-bc7ab4abae3b.png">
