### ISSUE TITLE
Numbered list items all remain at number 1

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#184]
![image](https://cloud.githubusercontent.com/assets/170947/18338159/0f967f9a-7597-11e6-9abe-e3f55221b8ae.png)

**Comment by benweet** [comment]
I can't reproduce this. Do you have it anytime?

**Comment by benweet** [comment]
Reproduced! Sorry about that.

**Comment by orschiro** [comment]
Do you know what causes the problem?

Thankfully,

-Robert
