### ISSUE TITLE
Suggestion: Default path for publishing to blog

### ISSUE THREAD

**Issue by ycmjason** [classeur/classeur#186]
Hello,

I think it makes perfect sense to have the default path set to the file.name.lowerCase().spaceToHyphen(). Then the user could edit that name to the desired path. 

What do you guys think?

Jason

**Comment by orschiro** [comment]
Dear @ycmjason,

Thank you for your suggestion!

Could you please give an example of how this would change from the current to the desired state?

What would have to change where and how would it affect the user?

Thankfully,

-Robert

**Comment by ycmjason** [comment]
Sure. But apparently to me now the BlogPost controller doesn't have the file in the scope? I couldn't figure the code myself.

In here,
https://github.com/classeur/classeur/blob/master/src/blogs/github/githubBlogPostForm.html#L14

``` javascript
<md-input-container>
  <label>File path</label>
  <input autocomplete="off" ng-model="form.subForm.filePath">
</md-input-container>
```

If we could pre-define `form.subForm.filePath` to be the `file.name`, this would be done.

This should not be hard. However, in

https://github.com/classeur/classeur/blob/master/src/blogs/blogs.js#L47

I think the file is not in scope when I inspect it with the debugger. So I guess we need to change something in its parent to make this happen. However I couldn't figure out where the parent is. HAHA.

Sorry for my limited knowledge.

I would recommend the following manipulation to the `file.name` to make it a valid file name.

``` javascript
file.name
  .toLowerCase()
  .replace(/ /g, '-') // replace spaces with dash
  .replace(/[!@#$%^&*()_+=~`\|\[\]\{\};:'",./<>?\\]/g, '') // remove punctuations
```

This is all I could do for now. I am sure it would not be hard at all if you are familiar with the infrastructure of this project. 

I hope this suggestion would be accepted and implemented.

**Comment by ycmjason** [comment]
Just realize I didn't quite answer @orschiro 's question. Let me make this clearer.

> Could you please give an example of how this would change from the current to the desired state?

The current implementation have an empty `filePath`, which is fine. But it makes perfect sense to have the `file.name` as the default value.

> What would have to change where and how would it affect the user?

This would not have much effect on the user experience. It's just an extra option that people could use. If that user wants a custom name, nothing will stop them from doing so. But I bet 70% of the time, people would just use the file name as the filePath.

**Comment by benweet** [comment]
Hi @ycmjason 
Fair enough, we can have that for the next release.
