### ISSUE TITLE
Very slow typing with large amounts of mathjax in document

### ISSUE THREAD

**Issue by asleepinthetrees** [classeur/classeur#187]
I love classeur, but for some reason it takes forever to type and update if I have a lot of math in the document, is this a known issue. If so will it ever be fixed? Its important that I can take my notes in math class and I really cannot be slowing down to wait for the UI to become responsive.

Regards,

**Comment by orschiro** [comment]
Dear @asleepinthetrees,

Thank you for your report. 

Can you please share the content of an example document with us so that we can try to reproduce the problem?

Thankfully,

-Robert

**Comment by benweet** [comment]
I've seen large documents that take a bit of time to render. However it should be fast once all the math expressions have been rendered (maybe 30 sec/1 min after opening the file).

Let me know if it doesn't.

**Comment by jakeoung** [comment]
Same problem if there many math equations to render.
