### ISSUE TITLE
Feature request: Copy content of exported template to clipboard

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#188]
As requested by Hubert,

Let's talk about the potential feature to copy the content of an exported template directly to the clipboard. 

I could imagine an integration as follows. 

Warmly,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18473957/d72bdb3c-79bf-11e6-8834-a8284f2f0fd5.png)

**Comment by VillageHubertChen** [comment]
Hi Robert,

Perfect! Thank you!

~Hubert
