### ISSUE TITLE
Rename Blogs to Publishing Platforms

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#190]
![image](https://cloud.githubusercontent.com/assets/170947/18502743/2ba89d28-7a59-11e6-99f7-33962eb50e21.png)

**Comment by benweet** [comment]
Hi @orschiro 
I don't really like using the term "platform" for that as it's already used to name the service/platform that hosts the blog:

<img width="475" alt="screen shot 2016-09-14 at 09 54 49" src="https://cloud.githubusercontent.com/assets/1005257/18505973/aa18c68a-7a61-11e6-80f4-f5b77670d6b4.png">

**Comment by orschiro** [comment]
@benweet what if we change it as follows?

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18506800/e68bc3c2-7a6d-11e6-9cae-e61eb619b8a9.png)

**Comment by benweet** [comment]
You don't get it. There are already 3 different concepts:
- **Blog post:** an article published on a blog
- **Blog:** a user site hosted by an online platform
- **Platform:** an online service that provides user site hosting, such as Blogger, Wordpress...

You want to mix the 2 last concepts together. It's confusing.

**Comment by orschiro** [comment]
Hi @orschiro
I don't really like using the term "platform" for that as it's already used  
to name the service/platform that hosts the blog:

<img width="475" alt="screen shot 2016-09-14 at 09 54 49"  
src="https://cloud.githubusercontent.com/assets/1005257/18505973/aa18c68a-7a61-11e6-80f4-f5b77670d6b4.png">
