### ISSUE TITLE
Blank screen shown in chrome desktop

### ISSUE THREAD

**Issue by rz-robsn** [classeur/classeur#198]
Hi,

When opening a document on chrome I only get an empty page with a blinking cursor even though my document has text ! The preview still show the text and as I try to type on the empty page, nothing is shown on screen but my changes are still shown when I toggle preview. The document displays just fine on safari and on the mac app (v1.7.1).

My Chrome version is 53.0.2785.116

Let me know if you need any more info.

**Comment by orschiro** [comment]
Thanks @rz-robsn!

I just tried it with the same Chrome version on Ubuntu 16.04 and it works just fine. 

Can you please try an incognito window?

-Robert

**Comment by rz-robsn** [comment]
@orschiro I just tried opening chrome via an incognito window and login and still have the same problem. Maybe it's due to the fact that I'm on MacOS ?

**Comment by orschiro** [comment]
Yes, maybe. Do you have problems with other websites, too?

@benweet do you have a Mac to test it?

-Robert

**Comment by rz-robsn** [comment]
I don't have problems with other websites on Chrome.

for reference, my macOS version is 10.11.6 .

**Comment by benweet** [comment]
No problem for me on OSX 10.11.6/Chrome 53.0.2785.116 I'm afraid.

Maybe try to disable your chrome extensions.
