### ISSUE TITLE
Sync Github/Jekyll content

### ISSUE THREAD

**Issue by justinkelly** [classeur/classeur#21]
Hi Classeur,

I'd like to use Classeur as a front end to a Jekyll blog hosted on Github

You can publish/upload from classeur - but it would be great if (like tinypress) it could sync all your posts - not just the ones created with classeur

Cheers

Justin

**Comment by benweet** [comment]
Hi @justinkelly ,
There is no plan for syncing with other platforms as Classeur has it's own synchronization mechanism. However, there is plan for a desktop application which can be used to edit local files (see #37, already available on OS X).

**Comment by ycmjason** [comment]
I think Classeur should really consider the ability to sync with jekyll! It would be an amazing feature!

**Comment by orschiro** [comment]
Dear @ycmjason,

You can publish to Github. 

Would that work to update a Jekyll blog?

Warmly,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18473387/fe734386-79bc-11e6-8fa2-e458fa99791e.png)

**Comment by ycmjason** [comment]
@orschiro 

Indeed, sorry for posting without really looking into the new version! Thank you and good job at classeur. It is officially my favorite markdown editor.

**Comment by orschiro** [comment]
Thank you for your positive words, @ycmjason! :-)

Warmly,

-Robert
