### ISSUE TITLE
Add password protection to files, folders and classeurs

### ISSUE THREAD

**Issue by emilio2601** [classeur/classeur#24]
I think password protection would be useful, I'd like to encrypt individual files, whole folders or entire classeurs.

**Comment by benweet** [comment]
What's the use case?

**Comment by emilio2601** [comment]
It could be useful to edit sensitive information, I think.

**Comment by benweet** [comment]
- If not shared publicly, your files are only accessible by you (or by people using your Google account). We assume Google accounts are securely protected with passwords or other authentication factors.
- Files and other user data are stored on AWS. We rely on Amazon VPC for data isolation in the data center and all data are accessed over SSL.

That said, we will provide on-premises instances shortly which will allow you to host your data in your private network.
