### ISSUE TITLE
Find bar gains focus only after animation

### ISSUE THREAD

**Issue by Swader** [classeur/classeur#29]
Due to the find bar's input field gaining focus only after the (imo way too slow) animation completes, the first taps for a fast typist are usually typos entered directly into the text where the cursor still was before the animation completed, upon hitting CTRL/CMD + F.

Suggested solution: make input field on find bar immediately focused when the "show find bar" function is called by any means.

**Comment by benweet** [comment]
Right. Will speed up the animation.
