### ISSUE TITLE
Severe performance issues on bigger, rich files

### ISSUE THREAD

**Issue by Swader** [classeur/classeur#31]
Here's a [post](https://app.classeur.io/#!/files/S6GYPTv5zvKEWVDq0GzJ) that's demonstrating severe lag, the more "south" you are when editing. Lag is slight, close to none, at the top of the post, but editing at the bottom kills it - especially in preview mode. It's also much milder when the doc is freshly opened, but the longer it's up and the more small edits are made here and there, the worse the performance will get.

**Comment by Swader** [comment]
Here's a gif, but it doesn't aptly demonstrate the problem. For reference, my typing speed is around 100 words per minute.
![classeur-slow](https://cloud.githubusercontent.com/assets/1430603/10871264/73438fa6-80e2-11e5-823a-00949f2b395a.gif)

The gif does show the jumping around that happens, too, though. I reckon this happens because images above in the post re-render but due to lag, the renders aren't instant so the text jumps around.

**Comment by benweet** [comment]
Weird. Images are supposed to be cached as I fixed #14. Are you running the app locally or do you use app.classeur.io?

**Comment by benweet** [comment]
Can you confirm `CL_VERSION.classeur` gives "0.11.0" in the js console?

**Comment by benweet** [comment]
Can't reproduce with version 0.11.

**Comment by Swader** [comment]
0.11.0, yes, online version.
The problem appears if the app has been open for a while - when fresh, it's rather fast still.

**Comment by benweet** [comment]
Ok, will investigate.

**Comment by benweet** [comment]
Think I've found the problem. Let me know if it's not any better with v0.12 (image flickering as well).
