### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Swader** [classeur/classeur#41]
Some documents qualify for several folders, when folders are used as "tags", in a way. For example, when I write for Diffbot, I put them in the Diffbot folder. When I write for SitePoint, I put them in the SitePoint folder. But then there are stages - Under Review, In Progress, etc. I could have separate folders for SitePoint - Under Review, SitePoint - In Progress, but that brings with it a whole lot of tab noise when you have many projects. Besides, sometimes something I write for Diffbot will get published on SitePoint, and then it would match both folders - which one do I put it in?

As a fix, I would recommend adding tags into the mix, so we can label documents with categories or milestones. I currently do this with prefixes.
<img width="643" alt="screenshot 2015-11-07 09 16 45" src="https://cloud.githubusercontent.com/assets/1430603/11014302/926647f0-8530-11e5-8bad-c4a885b1d7a9.png">

Either that, or adding subfolders into main folders - so we can have an "Under Review" subfolder in SitePoint. That still wouldn't allow me to add a post under both SitePoint and Diffbot, but would help.

**Comment by benweet** [comment]
Have you considered using different classeurs (using the switch on the top of the screen)? You could have a classeur for SitePoint, another for Diffbot, and then have folders named "Under Review", "In Progress" in each of them.

**Comment by Swader** [comment]
I had no idea this feature existed, thanks, that solves it with subfolders!

**Comment by benweet** [comment]
BTW, one folder can be shared by multiple classeurs, using `+` > `Import folder...`.

**Comment by Swader** [comment]
That's even cooler. Thanks!
