### ISSUE TITLE
Going Premium - How to?

### ISSUE THREAD

**Issue by torbjornlager** [classeur/classeur#47]
I decided to take the plunge so I paid for Premium yesterday, but still I don't seem to be able to export markdown files to PDF etc. And the app is still nagging me about going Premium. How can I use the Premium features?

**Comment by benweet** [comment]
Hi @torbjornlager,
Yeah, it looks like there was an issue with the processing of your payment. We're investigating.
Sorry about that.

**Comment by benweet** [comment]
I just canceled the subscription and issued a refund. Can you try again?
Should work better now.

**Comment by torbjornlager** [comment]
Yes, seems to work. Thank you!
