### ISSUE TITLE
Error when exporting to PDF

### ISSUE THREAD

**Issue by torbjornlager** [classeur/classeur#49]
A document containing the following Markdown character sequence. 

P~2~

causes the export to PDF to fail with the following message:

! Package inputenc Error: Keyboard character used is undefined (inputenc) in inputenc

Like there's an invisible character between 'P' and '~'!

**Comment by torbjornlager** [comment]
AFAIK, the invisible char is ascii 30.

**Comment by torbjornlager** [comment]
..
The char between the two periods is also an invisble one, ascii 11. Breaks export too, with same error. Again, I don't know where it came from.

**Comment by benweet** [comment]
Do you know if these characters come from an imported file or they were inserted by Classeur?

**Comment by torbjornlager** [comment]
No, sorry, I don't know. What I do know is that the long document that I'm working on has been assembled from pieces here and there, so the invisibles MAY appear as a consequence of this.

But does it really matter? I seems to me that Classeur should handle the situation even if a user accidentally pastes in content containing invisible chars. Maybe all you need to do is to remove them from the markdown before processing a document?

**Comment by benweet** [comment]
Yep, that's fine. Just wanted to be sure the bug was not in the editor.
Will try to find the exhaustive list of chars pandoc doesn't like.

**Comment by torbjornlager** [comment]
Hi again,

I don't understand why you don't filter out ALL non-printable chars berfore sending to Pandoc? Characters 0-31 that would be I think, except line breaks and probably the tab. It should't be more than 20 minutes work, at most. :-)

I'm getting kind of sick of removing them myself before exporting to PDF. Fortunately, I found a tool that does it for me, but you make me cut and paste twice and I shouldn't have to do that. Besides, not every one of your users can be expected to find such a tool.

https://www.juniper.net/documentation/en_US/idp5.1/topics/reference/general/intrusion-detection-prevention-custom-attack-object-extended-ascii.html

Cheers,
Torbjörn

**Comment by benweet** [comment]
Removing characters 0-31 would remove end of lines, tabs...
PDF generation is being refactored to address multiple problems, so it will probably require a few days to have that fixed.
