### ISSUE TITLE
Files not accessible 

### ISSUE THREAD

**Issue by TomBous** [classeur/classeur#52]
Hi, 

I've got a weird bug today using Classeur.

**Story** : First, when i tried to open some of my files, i got a notification saying : "You appear to be offline". 
I tried to re-launch Google Chrome (even reboot my PC, just in case), but the bug was still there. 
So i tried deleting one of the problematic files, and then recover it, without success. I got a notification saying something like "recover of the file pending". 
Then, as the deleted file didn't appear to recover, i restarted Chrome to be sure it was lost. 
Now, when i try again to open the problematic files i get a different notification that says : "File not accessible : {name of the file}".

I'm unable to found a pattern on this bug. It don't seems to be related to a sub-folder bug, as some files works in the same subfolder.

**Context** : Before using Classeur i was on StackEdit. Basically, my switch to Classeur was splitting (copy/pasting) parts of large documents into smaller files in Classeur.

**Question** : Is it possible to recover the files i'm unable to open ? SQL command ?

I hope you understand my english, and I am at your disposal for any further information, clarification or solutions to test. 

Thanks in advance !

Edit : I don't know if its matter, but the bug appears to only affect one of my folders, which is the one that have lots of subfolders (9).

**Comment by benweet** [comment]
Hi @UltimaTom 

Sorry about that. You can try to retrieve it via the REST API:
http://classeur.io/help/rest-api/

Can you provide us with the file ID (the ID in the address bar) so that we can investigate the issue? You can send this by email: contact@classeur.io. We will try to recover the file and send it back to you.

Thanks.

**Comment by TomBous** [comment]
Hi @benweet,

I'm not a programmer, but we did investigate on the local sqlite database with a friend. We manage to access the "working" files data but for the "non-working" ones, no data was present ; only the title was there. 

Here is an example of file id that was lost : AKh2BHtQ7cfTj9mRGb76.

Thanks again for your help.

**Comment by benweet** [comment]
@UltimaTom I'm sorry the file didn't get synchronized. This can happen if you create more than 30 files while offline. Did you notice any network issue? (there is a crossed cloud icon on the right side of the editor when offline)

**Comment by TomBous** [comment]
@benweet The synchronization failure is my fault... Indeed i created more than 30 files, but above all, at the time i didn't sign on with my google account (don't wanted to give more information on my web usage to Google) and there was no other way to register.

I don't remember the cloud icon, but as i wasn't registered i imagine that the icon was there.

**Comment by benweet** [comment]
We'll try to make the icon more visible then and maybe add more explanation about the synchronization.

**Comment by TomBous** [comment]
@benweet That is great, and I understand that the synchronization could have been a work around to the bug, but bug is still there. Maybe you should add a disclaimer saying that if you don't sign on your data could be lost ?
