### ISSUE TITLE
pandoc: Unable to convert 

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#54]
Dear @benweet,

I just tried to export a document to PDF but received the following error:

```
pandoc: Unable to convert `/tmp/tex2pdf.96/5d424bc6132b73039c2e9740a900ba6606b4179a.shtml' for use w
```

The document contains some sensitive information. Therefore, I cannot share it unfortunately. 

Any steps I can do to further debug the problem?

Thankfully,

~ Robert

**Comment by benweet** [comment]
Hi @orschiro 
Can you try to localize the problem by removing parts of the file and eventually share only the paragraph that is causing the error?

**Comment by orschiro** [comment]
@benweet 

I identified the problem. 

It was the following code:

```
![](https://photos-3.dropbox.com/t/2/AAC6acqUywa1KqYUWovVjFeaCepN-BcUPESgs40KtzjTLQ/12/8902804/png/32x32/1/_/1/2/Signature.png/EJix0AYY8Z4NIAcoBw/idusCMemHpOcDRptplGUTPEmdYK3ninaYXKm0StcFGA?size=1024x768&size_mode=3)
```

Apparently, Pandoc has issues accessing an image that is hosted on my private Dropbox. 

Is it possible for Classeur to support local image paths? 

For example, I don't want my signature image to be uploaded onto Imgur but prefer to reference it locally.

**Comment by benweet** [comment]
You could use data uri:

```
![red dot](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```

**Comment by orschiro** [comment]
Can the data uri reference to a local file?

If not, then it doesn't solve the problem of sensitive images not being hosted on public file hosting, I'm afraid.

**Comment by benweet** [comment]
Pandoc is run on server side, it won't access any data stored on your local machine.

Data uri is self-contained (the whole image data is contained in the uri in base64). So the image will be hosted by the markdown file itself (eventually it will be saved on Classeur servers, but not accessible publicly).

Hope it helps.

**Comment by orschiro** [comment]
It works! Thanks for your help. 

I used [duri.me](http://duri.me/) to convert the image into base64 code. 

The only downside is that the pasted code is very long and takes up a lot of space in the document.

**Comment by benweet** [comment]
Closing this one as I don't see any way for pandoc to access private external images.

**Comment by orschiro** [comment]
Thanks for bringing this to an end!

The URI method works well enough and should maybe added to the documentation for private-sensitive users. 

~ Robert
