### ISSUE TITLE
More than 6 classeurs causes scrolling glitch

### ISSUE THREAD

**Issue by arm32x** [classeur/classeur#57]
When I have more than 6 classeurs on the menu, scrolling down messes up the images.

**Screenshot:**
![screenshot 2015-12-16 at 9 49 03 am](https://cloud.githubusercontent.com/assets/15364665/11843977/5ae0ec72-a3da-11e5-81b5-4abb8dfb4a92.png)

> **Note:**
> It's the background tabs on the _classeurs_ glitching out, the program is still completely usable.

**Comment by cummconn053** [comment]
![screenshot 2015-12-16 at 9 49 03 am](https://cloud.githubusercontent.com/assets/15364665/11843961/4777ddc6-a3da-11e5-9c61-8f364bd64724.png)

**Comment by benweet** [comment]
Reproduced. Looks like a Chrome issue though. Will investigate.

**Comment by benweet** [comment]
Should be fixed with version 0.18.

**Comment by arm32x** [comment]
Thanks! It is fixed now!
