### ISSUE TITLE
Syncing with account didn't work properly. Files now all untitled

### ISSUE THREAD

**Issue by zweicoder** [classeur/classeur#64]
Was using Classeur before I changed my computer while logged into my Google account. Now that I'm logging in from another computer via the same Google account, some info is lost:
-  Files there are all 'Untitled' now despite them retaining the raw content. 
- Existing files are no longer grouped under their folders

Really unsure what exactly caused this bug, raising an issue just to alert the team. Tell me if more clarification is needed!

**Comment by benweet** [comment]
Sorry about that. Does a sign out and a clear data (from the settings) fixes the problem?

**Comment by zweicoder** [comment]
Nope

**Comment by zweicoder** [comment]
Actually I'm dual booting Windows with Linux and it works fine on Linux, so it might be a Windows issue. Closing this as my problem is resolved!
