### ISSUE TITLE
Allow custom CSS or inline style tag

### ISSUE THREAD

**Issue by jacobq** [classeur/classeur#68]
While I love markdown in general, I've occasionally wished I could throw in a style tag or otherwise apply some custom CSS so that I could add some niceties to my content. For example, I might make a list of colors used for a product/brand and want to show a circle filled with a sample of that color. As I understand it, markdown allows inline HTML, so I think this should be OK. Does this cause deep/technical challenges for the implementation of classeur (or stackedit, for that matter)?

**Comment by ghost** [comment]
Stackedit can do this, but it's a bit awkward.  I will have to revert back to Stackedit until styles become available in Classeur. As a suggestion, add a button to the toolbar, with a list of [style] classes to add to, edit/define,  and choose from,  for selected text. Cheers, Steve

**Comment by arm32x** [comment]
I so want to be able to have red text without an external style Chrome extension!

**Comment by benweet** [comment]
Custom CSS and custom extensions as implemented in StackEdit are subject to malware. I would recommend you to use browser extensions for that as there is no plan to support it inside the app.

Note that you can still export and publish using custom templates, including custom CSS and custom Handlebars helpers.
