### ISSUE TITLE
LaTeX - Issues with parsing allign environment

### ISSUE THREAD

**Issue by ketchers** [classeur/classeur#69]
$$\begin{align}
x&=y\
y&=x
\end{align}$$

gets translated to LaTeX as 

[\begin{align}
x&=y\
y&=x
\end{align}]

This is invaild LaTeX it should just be

\begin{align}
x&=y\
y&=x
\end{align}

There should be no [ or $$ at all. This causes export to PDF to fail.

**Comment by benweet** [comment]
Correct me if I'm wrong but I think this is the default behavior of pandoc.
