### ISSUE TITLE
Classeur doesn't show up in browser

### ISSUE THREAD

**Issue by tmr232** [classeur/classeur#7]
After following the instructions in the readme, I get the following error loading the page in chrome:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module classeur.app due to:
> Error: [$injector:modulerr] Failed to instantiate module classeur.core.analytics due to:
> TypeError: Cannot read property 'googleAnalyticsTrackingId' of undefined
>     at http://localhost:11583/app-min.js:74578:33
>     at Object.invoke (http://localhost:11583/app-min.js:4478:17)
>     at runInvokeQueue (http://localhost:11583/app-min.js:4384:35)
>     at http://localhost:11583/app-min.js:4393:11
>     at forEach (http://localhost:11583/app-min.js:336:20)
>     at loadModules (http://localhost:11583/app-min.js:4374:5)
>     at http://localhost:11583/app-min.js:4391:40
>     at forEach (http://localhost:11583/app-min.js:336:20)
>     at loadModules (http://localhost:11583/app-min.js:4374:5)
>     at createInjector (http://localhost:11583/app-min.js:4299:11)
> http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=classeur.core.analy…0createInjector%20(http%3A%2F%2Flocalhost%3A11583%2Fapp-min.js%3A4299%3A11)
>     at http://localhost:11583/app-min.js:68:12
>     at http://localhost:11583/app-min.js:4413:15
>     at forEach (http://localhost:11583/app-min.js:336:20)
>     at loadModules (http://localhost:11583/app-min.js:4374:5)
>     at http://localhost:11583/app-min.js:4391:40
>     at forEach (http://localhost:11583/app-min.js:336:20)
>     at loadModules (http://localhost:11583/app-min.js:4374:5)
>     at createInjector (http://localhost:11583/app-min.js:4299:11)
>     at doBootstrap (http://localhost:11583/app-min.js:1657:20)
>     at bootstrap (http://localhost:11583/app-min.js:1678:12)
> http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=classeur.app&p1=Err…0at%20bootstrap%20(http%3A%2F%2Flocalhost%3A11583%2Fapp-min.js%3A1678%3A12)

And I can see nothing but a gray screen. What can I do to solve this?

**Comment by benweet** [comment]
Can you rebase and try again?
Thx.

**Comment by tmr232** [comment]
Works great, thanks. Only the font missing now...

**Comment by benweet** [comment]
And now?
