### ISSUE TITLE
Chinese font in Windows 10 is not good for reading.

### ISSUE THREAD

**Issue by mlxzlas** [classeur/classeur#70]
Classeur works great, just the Chinese font using right now is very hard to read (When launch it in Windows 10 Chrome), But it is good when using Linux. I made a pic to explain:
![Classeur Font](https://farm2.staticflickr.com/1560/23600443924_d791ed8c96_o.png)
English font is **sans serif** in both Windows and Linux, but Chinese font in Windows is **serif**, and **sans serif** in Linux.

So, is there a possibility to make some change or make a option? thx a lot.

**Comment by mlxzlas** [comment]
and Chinese font no bold effect

**Comment by benweet** [comment]
It's rather a problem with Chrome. The issue can be reproduced on this page:
http://windows.microsoft.com/en-IE/windows/language-packs#lptabs=win10

Zooming the page by 150%, the font become serif as your screenshot. Works fine on IE.

A workaround is to reduce the font size in Classeur's settings.
