### ISSUE TITLE
Metadata API endpoint acts like an echo service for nonexistent objects

### ISSUE THREAD

**Issue by zbentley** [classeur/classeur#74]
While testing [http://zbentley.github.io/classeur-api-client/](http://zbentley.github.io/classeur-api-client/), I noticed that if you supply a nonexistent ID to a metadata API (e.g. `curl https://app.classeur.io/api/v1/metadata/files?id='something_nonexistent' -u user:key`) it doesn't give an error or indication of the failure in the results, it just returns a JSON object with only the ID in it, e.g. `{ id: 'nonexistent' }`.

That seems buggy. Metadata failure should probably throw a 400, or at least return something in the JSON nonexistent entities that indicate that they don't exist. If the "echo service"-like behavior is necessary for something, it should at least be documented in the REST API docs.

You can repro this issue with CURL, or by [running the integration tests](https://github.com/zbentley/classeur-api-client/blob/master/doc/DeveloperGuide.md) for my module. Tests that hit this bug are marked with `skip` in the releases (they're the only ones that are), but are failing at HEAD.

FYI the github pages doc refresh for the module is lagging hard as of this writing; use the 0.1.1 doc or just the [repo](https://github.com/zbentley/classeur-api-client) if you need it.

**Comment by benweet** [comment]
Yes, the documentation lacks some description about the returning objects.

Basically, the metadata API should not fail if only one id fails, as the caller may still want to have the result of the working ids. So a status per id and eventually an error message could be useful.

**Comment by zbentley** [comment]
Documentation and an error message both seem useful. This might also be a good use case for HTTP partial-success codes (206) as an additional status indicator, for example:
- A single nonexistent entity:
  - Example request: `/metadata/files&id=nonexistent`.
  - HTTP response code: 206, 400, or 404.
  - Example body:`[{ id: 'nonexistent', error: 'ENOENT' }]`.
- Existent and nonexistent entities:
  - Example request: `/metadata/files&id=nonexistent,existent`.
  - HTTP response code: 206.
  - Example body: `[{ id: 'nonexistent', error: 'ENOENT' }, {id: 'existent', <other metadata fields>}]`.
- Existent entity or entities:
  - Example request: `/metadata/files&id=existent`.
  - HTTP response code: 200.
  - Example body: `[{id: 'existent', <other metadata fields>}]`.

**Comment by benweet** [comment]
@zbentley Status 206 stands for "Partial Content" which rather indicates that the response contains only [a range of the actual result](https://tools.ietf.org/html/rfc7233#section-4.1) (may be appropriate for paging).

I think 200 is fine considering it's kind of [bulk operation](https://groups.google.com/d/msg/api-craft/86i25AMXM7c/SuQb--Ty9EoJ).

**Comment by benweet** [comment]
Hi @zbentley 
We've released a new version of the REST API. Unfortunately there are a lot of changes.
Let me know if you have issues with it.

**Comment by zbentley** [comment]
Will do; sometime in the next month I'll add support for the new API to my client packages. Thanks!
