### ISSUE TITLE
Support for align right?

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#80]
Dear all, 

I know this is technically not a problem of Classeur as Markdown does not have any native support for `text-align: right`. Yet I was wondering if anyone has thought of a solution to alignining text to the right.

Thankfully,

~Robert

**Comment by benweet** [comment]
Hi Robert,
Just released the 1.0. I fixed a bug that was preventing alignment of html element. Now you should be able to use plain html like this:

```
<div align="right">
blah blah
</div>
```

**Comment by orschiro** [comment]
Great!

How about adding a visual button that inserts this plain text?

People are used to visual icons, especially for elementary things such as align right.

Thankfully,

~Robert

**Comment by benweet** [comment]
The problem is that it's not really supported by the markdown syntax, meaning the content of the div has to be plain html, no markdown support inside it.

**Comment by orschiro** [comment]
How can we best propose requests like these to the Markdown syntax?

~Robert

**Comment by benweet** [comment]
Not sure. The format is open but there have been attempts to standardize it. The markdown library we use is [markdownit](https://github.com/markdown-it/markdown-it) which is very customizable, but at the same time, it tries to stay as close as possible to the [common mark initiative](http://commonmark.org/).

**Comment by orschiro** [comment]
I see. Thanks for the information!

I will see what I can do to start a discussion at the right channel.

~Robert

**Comment by orschiro** [comment]
For referencing, started a discussion at [talk.commonmark.org](http://talk.commonmark.org/t/support-for-align-right/2042).
