### ISSUE TITLE
Problems with specific Input

### ISSUE THREAD

**Issue by chrbaeu** [classeur/classeur#85]
I had problems with one of my files. Tried to make a small example with the problem. Classeur fails with this content and freezes:

_Test_
Test $G$, $G$ $G$, $G$, $G$ $G$.
_Test_
Test $G$, $G$, $G$, $G$, $G$.
Test $G$, $G$, $G$, $G$, $G$.
Test $G$, $G$, $G$ . $G$.

**Comment by benweet** [comment]
Should be fixed with the latest 1.0.
