### ISSUE TITLE
How to move a map between different Classeurs?

### ISSUE THREAD

**Issue by orschiro** [classeur/classeur#87]
Hi all, 

I might have missed this one but how can I move a map (collection of files) from one Classeur to another?

Thankfully,

~Robert

**Comment by benweet** [comment]
Hi Robert,
In the coming release, orphan files (not in any folder) will always be in the default Classeur. For folder files, you will have to move the folder from one Classeur to another, or drag and drop files into the new Classeur folder.
I hope that makes sense.

**Comment by orschiro** [comment]
Dear @benweet,

Let me try it out then!

Thanks,

~Robert
