### ISSUE TITLE
Connect to Tumblr blog?

### ISSUE THREAD

**Issue by al-the-x** [classeur/classeur#89]
On the home page, Tumblr is listed in the blogging platforms that Classeur supports:

![Feature: Upload to Tumblr](https://cloud.githubusercontent.com/assets/96015/13685502/c882ef2c-e6de-11e5-923e-9cc6ae2f13c6.png)

But when attempting to link a blog via Settings, only Blogger, GitHub, and WordPress are presented:

![What, no Tumblr?](https://cloud.githubusercontent.com/assets/96015/13685551/f68e4e5c-e6de-11e5-8001-9bf17d579065.png)

Is Tumblr support _planned_...?

**Comment by al-the-x** [comment]
I dug a little bit in the source to find the interfaces for Blogger, GitHub, and WordPress, but I don't understand the architecture well enough to submit a PR...

**Comment by benweet** [comment]
This is under development. The back-end needs to support it.

**Comment by al-the-x** [comment]
Closed as the project has been abandoned.
