### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Jack-Kingdom** [classeur/classeur#90]
When I publish post to Blogger with styled HTML, this post will shelter navigation bar and post name.
I use Chrome and there is an error in console.

![screenshot from 2016-03-11 22 37 05](https://cloud.githubusercontent.com/assets/10584772/13705374/8707549a-e7db-11e5-9273-f8b314d93f78.png)

**Comment by benweet** [comment]
Hi @Jack-Kingdom 
Styled HTML is meant for standalone HTML file export. For blogs, you have to use the plain HTML.
