### ISSUE TITLE
User data not synchronized between Chrome Stable and Chrome Beta

### ISSUE THREAD

**Issue by jwarner112** [classeur/classeur#91]
Hello,

Recently I uninstalled Chrome 49 Stable and installed Chrome 50 Beta instead. When logging into Classeur, none of my files were synchronized. To be sure that the Browser was the issue, I reinstalled Chrome 49 Stable and immediately logged into Classeur to find all of my files immediately. Refreshing does not resolve the sync issue-- the files simply aren't found for Classeur on Chrome Beta.

Thanks,
Jeff W.

**Comment by ghost** [comment]
If you sign into Classeur with Google on Chrome Stable, sync your local files to the cloud, and sign in with Google on Chrome Beta, it should work. Chrome Beta does not use the same cache file as Chrome Stable; therefore, you cannot get your Chrome Stable cache info (like history, extensions, etc.) in Chrome Beta.

Hope this helps!

**Comment by benweet** [comment]
I don't reproduce the issue on Chrome Canary.
