### ISSUE TITLE
"You appear to be offline" error when using localstorage

### ISSUE THREAD

**Issue by ghost** [classeur/classeur#92]
I'm not signed into google b/c the sign-in is blocked on my school computer.
![image](https://cloud.githubusercontent.com/assets/8107485/13778173/9bddcafa-ea8a-11e5-9888-7c3c7bb26e89.png)
This only started happening when Classeur 1.0 came out. The day before it was working fine. HELP! I USE CLASSEUR FOR ALL OF MY SCHOOLWORK!

**Comment by benweet** [comment]
This error message means your data can't be synchronized with the server. It should not prevent you from using the app.
Please let me know if there are issues.

**Comment by ghost** [comment]
Sorry to bother you again, but I found out something else. When I click on the first document (K11.1) in the list, which was created on Friday, it does the error. But when I click the one before, which was created on Thursday, It opens.
![image](https://cloud.githubusercontent.com/assets/8107485/13788107/f5bd2348-eab4-11e5-931c-bfb7d27ff92c.png)

**Comment by ghost** [comment]
I think that this has only been happening since the 1.0 update. Is there any dependence on external sources to open a document?
