### ISSUE TITLE
Unable to remove empty comment

### ISSUE THREAD

**Issue by vagelim** [classeur/classeur#99]
When changing the text that is highlighted by a comment, occasionally the comment will become empty. In that case, the user is unable to delete the blank comment. Though that is only a minor inconvenience, the bigger problem is that a significant portion of the text that follows the former comment is then highlighted.

**Comment by pymander** [comment]
I am also running into the blank comment problem. We are trying to use Classeur collaboratively, and being unable to remove empty comments is hindering our review process and causing a lot of confusion.

**Comment by benweet** [comment]
That's priority 1 for the next release.

**Comment by benweet** [comment]
Should be fixed with version 1.2.2.
